import type { Metadata } from "next";
import "./globals.css";
import Header from "@/templates/Header";
import Footer from "@/templates/Footer";

export const metadata: Metadata = {
  title: "Compressores Brasil",
  description: "Generated by create next app",

};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <head>
        <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
      </head>
      <body className="flex flex-col bg-black text-white min-h-screen">
        <Header />
        <main className=" pt-24"> {/* espaço para o header + subheader */}
          {children}
        </main>

        <Footer />

      </body>
    </html>
  );
}
